### ISSUE TITLE
Set badge numbers

### ISSUE THREAD

**Issue by hhaider** [infobip/mobile-messaging-cordova-plugin#1]
In the old infobip cordova plugin there was a feature to set the number of badges for ios.
`push.setBadgeNumber(num); `
Will a similar feature be added to the new infobip cordova plugin?

**Comment by stanislavin** [comment]
Current version of cordova plugin supports badge API only at server level and there are no plans to support it at client side. However you can use other plugins to set badge on iOS (like https://github.com/katzer/cordova-plugin-badge/).

You can also find reference of server API below:

Single push notification: https://dev.infobip.com/docs/send-push-notifications (https://dev.infobip.com/docs/send-push-notifications#section-notification-options)

Bulk push notifications (scheduling, campaigns, large amount of messages): https://dev.infobip.com/docs/send-bulk-push-notificatons (https://dev.infobip.com/docs/send-bulk-push-notificatons#section-notification-options)

If you can provide your use-case, we will discuss it within the team and will see if can address it in our feature roadmap for cordova plugin.

**Comment by hhaider** [comment]
My use case is setting badge number to 0 when the the app opens after the user taps on the push notification.
Currently with my test notifications the badge number is stuck to 1.

**Comment by stanislavin** [comment]
iOS library inside this plugin does not set badge on its own, neither cordova part of the plugin. So now it can only be set through http api.

As a temporary solution I suggest you to use https://github.com/katzer/cordova-plugin-badge/. Then you will be able to call
`cordova.plugins.notification.badge.clear()` to clear the badge whenever you need it. I checked it with our library and there would be no conflicts.

Let me know if that works for you and I would close this issue for now. I will report here when we have badge available within our plugin.

**Comment by hhaider** [comment]
Ok will do that, thanks.

**Comment by stanislavin** [comment]
Closing for now, to be updated with badge details once available.

**Comment by MerkulovDev** [comment]
Please add this to the instructions as I'm facing a similar issue.
