### ISSUE TITLE
Build error after adding Notification Service Extension 

### ISSUE THREAD

**Issue by solinder** [infobip/mobile-messaging-cordova-plugin#11]
Hello.
I add Notification Service Extension to my iOS project and have trouble with command `ionic cordova build ios`.
My steps:
1. I add platform by `ionic cordova platform add ios`
2. Open .xcodeproj file in Xcode. Add this settings to main target as you described here: 
https://github.com/infobip/mobile-messaging-cordova-plugin#quick-start-guide 
in step "4. Configure your iOS project"
3. Add new target for Notification Service extension as you described here:
https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10#creating-a-new-notification-service-extension
4. Set up my new target:
https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10#cordova-ios-project

I should mention that i have the last version of Xcode - 9.4.1, and there are no such settings for the new target as on your screenshots:
https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Images/NotificationServiceExtensions/extension_framework_search_paths.png?raw=true
https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Images/NotificationServiceExtensions/Troubleshooting/ats.png?raw=true

5. I run `ionic cordova build ios` in the command line and get such error:
![2018-07-18 18 52 08](https://user-images.githubusercontent.com/26798247/42893637-93fa8488-8abd-11e8-94be-437546d1b0fd.png)

Could you advice me something please? Thanks.

**Comment by kas-kad** [comment]
@solinder hello, please look carefully
<img width="483" alt="image" src="https://user-images.githubusercontent.com/1947169/42894494-a5836240-8abf-11e8-820d-18c48cdafbeb.png">

**Comment by kas-kad** [comment]
Regarding ATS, you have to manually add the Apple Transport Security settings into your Info.plist from the Info tap

**Comment by solinder** [comment]
Thank you for describing. I set this two settings that I lost before:
![2018-07-18 20 31 29](https://user-images.githubusercontent.com/26798247/42897832-e656e292-8ac9-11e8-9ac3-95c1f7d5da96.png)
![2018-07-18 20 31 44](https://user-images.githubusercontent.com/26798247/42897837-ecfdfe32-8ac9-11e8-8ac9-4f04e157e040.png)

But the error still remains:
![2018-07-18 20 33 40](https://user-images.githubusercontent.com/26798247/42897853-fb541ebc-8ac9-11e8-81c8-e8b71b2545ed.png)

**Comment by kas-kad** [comment]
Can you post the whole output because on your screenshot the error description is truncated.

**Comment by solinder** [comment]
![2018-07-18 20 42 11](https://user-images.githubusercontent.com/26798247/42898187-1fd86d78-8acb-11e8-8a85-e6131e91652a.png)
![2018-07-18 20 42 27](https://user-images.githubusercontent.com/26798247/42898190-223a9bcc-8acb-11e8-8f2a-0166b287dfb3.png)
Is it enough or I should show all output?

**Comment by kas-kad** [comment]
@solinder what is the minimum deployment target for the NotificationExtension target?

**Comment by kas-kad** [comment]
NotificationExtension target should have minimum deployment target 10.0. It's either cordova or ionic changes this setting. This is a new issue. We'll see what we can do.

**Comment by solinder** [comment]
I set up deployment target for the whole application to 10.0. And the previous error goes away.
But it is sad if application should support iOS 10+. So please let me know if you will find out some ways to support 9.0.

Also could you explain me please, what settings I should set when running `xcodebuild build` and `xcodebuild archive`?
I'm talking about parameters: 
scheme - I think, it should be extension, right?
target - I think, it should be extension, right?
PRODUCT_BUNDLE_IDENTIFIER - of main target or of extension target?
PROVISIONING_PROFILE - of main target or of extension target?

**Comment by kas-kad** [comment]
NotificationExtension must have it's own provisioning profiles set up for Extension App ID. Generate them on  Developer portal, download and setup through Xcode. This is the usual procedure of developing Notification Service extension.

**Comment by solinder** [comment]
I have already done all this things according to your instructions. I have App group, App ID, certificate and provisioning profile for extension. 
When i set this all ib Xcode and run on device everything is ok. 
But i want to export archive and do this from the command line by command that i mentioned ib previous message. And the question is what parameters should i use?
I have tried several combinations and always get errors.

**Comment by kas-kad** [comment]
scheme - main app
target - main app target
PRODUCT_BUNDLE_IDENTIFIER - main app
CODE_SIGN_IDENTITY - iPhone Distribution
PROVISIONING_PROFILE - of main target

**Comment by kas-kad** [comment]
In order to avoid these issues 
https://github.com/infobip/mobile-messaging-cordova-plugin/issues/11#issuecomment-406015877

just annotate your UNNotificationServiceExtension subclass with `@available(iOS 10.0, *)`:

```
@available(iOS 10.0, *)
class NotificationService: UNNotificationServiceExtension {
...
}
```

**Comment by solinder** [comment]
Even if I use settings that you advice:
```
xcodebuild build `
    ` -project "platforms/ios/MyApp.xcodeproj"`
    ` -scheme "MyApp"`
    ` -archivePath "platforms/ios/MyApp.xcarchive"`
    ` -destination "generic/platform=iOS"`
    ` -target="MyApp"`
    ` ENABLE_BITCODE=NO`
    ` PRODUCT_BUNDLE_IDENTIFIER="THERE_IS_APP_ID"`
    ` PRODUCT_NAME="MyApp"`
    ` DEVELOPMENT_TEAM="THERE_IS_OUR_TEAM_ID"`
    ` CODE_SIGN_IDENTITY="iPhone Distribution"`
    ` PROVISIONING_PROFILE="THER_IS_APP_PROFILE_UUID"`
    ` IPHONEOS_DEPLOYMENT_TARGET="9.0"
```
I get error:
```
Check dependencies
Code Signing Error: Provisioning profile "extension Distribution Profile" has app ID "THERE_IS_EXTENSION_ID", which does not match the bundle ID "THERE_IS_APP_ID".
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.4'
```

I thought that maybe I have done something wrong while setting up project in Xcode. But when running on device from Xcode everything is ok, push notifications successfully comes to application.

**Comment by kas-kad** [comment]
@solinder try no to specify any profiles since they are specified in the project

**Comment by stanislavin** [comment]
@solinder let me know if issue still happens for you.

**Comment by solinder** [comment]
The problem is not actual now. Thank you.

**Comment by stanislavin** [comment]
Closing
