### ISSUE TITLE
Error "Could not find org.infobip.mobile.messaging.api:infobip-mobile-messaging-android-sdk"

### ISSUE THREAD

**Issue by Eleferen** [infobip/mobile-messaging-cordova-plugin#13]
I used your plugin version 1.0.6

In config.xml declaration looks like:

```
<plugin name="com-infobip-plugins-mobilemessaging" spec="^1.0.6">
    <variable name="ANDROID_FIREBASE_SENDER_ID" value="1111111111" />
    <variable name="ANDROID_SUPPORT_VER_OVERRIDE" value="false" />
    <variable name="ANDROID_GMS_VER_OVERRIDE" value="false" />
</plugin>

```
And when running `ionic cordova build android` or `ionic cordova run android` i have such error:

![error](https://user-images.githubusercontent.com/15795413/53171603-48222380-35f4-11e9-93ad-a3dcfcbb0000.png)

Can you advise me something? Thanks.

Windows10
Cordova@7.1.0
Ionic@3.20.0
Node@8.11.3
Npm@6.4.1

**Comment by stanislavin** [comment]
There might've been some issue with bintray or publishing, but the latest version of the plugin bundles 2.0.9.27 version of the sdk and I see that the dependency from your log is there https://bintray.com/infobip/maven/infobip-mobile-messaging-android-geo-sdk/2.0.9.27, so it would be great if you can just try the lates version of the plugin (1.0.12)  and see if it works.

**Comment by Eleferen** [comment]
The problem is not actual now. Thank you for your help. Issue could be closed.
