### ISSUE TITLE
Typescript type definition

### ISSUE THREAD

**Issue by chunhoong** [infobip/mobile-messaging-cordova-plugin#17]
Is there type definition available for Typescript? Would be glad if Infobip can release a set of type definition to ease the integration for Angular / Ionic developer.

**Comment by tjuric** [comment]
Hi @rephchunhoong,
currently we don't have the type definition for Typescript in our Cordova project, but we might provide a file from our side to ease the development (or you might check it up in native SDK libs if it's urgent for you now). 
We might schedule it for one of the future releases.

Regards, 
Tereza

**Comment by davidrock** [comment]
Any update on that?

**Comment by kostap13** [comment]
Hi @davidrock 

Now you are able to use typings:
```
npm install --save-dev @types/mobile-messaging-cordova
```

Or ionic integration:
```
ionic cordova plugin add add com-infobip-plugins-mobilemessaging --save
npm install @ionic-native/mobilemessaging --save
```

Hope it will helps you!
