### ISSUE TITLE
android:exported needs to be explicitly specified for element <receiver#org.infobip.mobile.messaging.geo.BootReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

### ISSUE THREAD

**Issue by TK2011-TH** [infobip/mobile-messaging-cordova-plugin#24]
Hi,

I am facing an issue after installing the package in my Ionic project. When I try to build my Android app, I receive the following error message:

'android:exported needs to be explicitly specified for element <receiver#org.infobip.mobile.messaging.geo.BootReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined.'

This issue is preventing me from building and deploying my app. I have checked my AndroidManifest.xml file, but I am unable to resolve this issue.

Can you please help me resolve this issue and provide any guidance or fixes that may be necessary? Thank you for your help.

**Comment by riskpp** [comment]
Hi @TK2011-TH are you using this version https://github.com/infobip/mobile-messaging-cordova-plugin/releases/tag/3.0.0-rc4 ?

We have android 12 supported only for that, please check migration guide https://github.com/infobip/mobile-messaging-cordova-plugin/wiki/Migration-to-version-3.x.x

**Comment by TK2011-TH** [comment]
Hi riskpp, still get the same errors about 'Manifest merger failed with multiple errors, see logs'. Seems like some how the package still merge unsupported receivers.

**Comment by TK2011-TH** [comment]
Hi riskpp,

Thank you so much, it works now.

Sorry, but I have encountered another issue, and I am not sure if I should open a new issue for it.

Before this, my app was already working with Firebase by using this package: https://github.com/chemerisuk/cordova-plugin-firebase-messaging. We already have our backend to send push notifications to the app.

After solving the Android 12 issue, even Im able to build the app successfully, but it kept crashing constantly, not sure is it possible to make it works together. If not, and I need to use only the Infobip package, will I still be able to send messages from my own backend (which requires the Firebase device token), or do I need to move to Infobip completely?

**Comment by riskpp** [comment]
Hi @TK2011-TH please close this issue and create new one, also provide crashlog, in general it's possible to use infobip native sdk together with other push provider, we have this articles you may check 
https://github.com/infobip/mobile-messaging-sdk-android/wiki/How-can-I-achieve-handling-by-Infobip's-Firebase-and-my-Firebase-messaging-service%3F
https://github.com/infobip/mobile-messaging-sdk-android/wiki/Android-Manifest-components

But for cordova might be tricky, you may need to perform some native coding for it.

Regarding sending messages from your backend, you may do it but they won't be handled properly by infobip sdk.
