### ISSUE TITLE
Crashes on push receiving

### ISSUE THREAD

**Issue by MerkulovDev** [infobip/mobile-messaging-cordova-plugin#25]
The push was successfully received, but upon clicking it, a crash window appears. Here is the message from the logs:

MobileMessaging: closure #1 in closure #1 in static MobileMessaging.didReceiveRemoteNotification(_:fetchCompletionHandler:)

<img width="1116" alt="image" src="https://github.com/infobip/mobile-messaging-cordova-plugin/assets/33004175/0753f027-c8cc-4655-9916-0cf4b8d9a492">

It's interesting to note that there are no problems on iOS 15, but on iOS 16 and later, the app crashes.

app Ionic Cordova.
"com-infobip-plugins-mobilemessaging": "2.5.1"
"@awesome-cordova-plugins/mobile-messaging": "6.4.0"
"cordova-plugin-firebasex": "16.1.0"

**Comment by riskpp** [comment]
Could you please try to use this version https://github.com/infobip/mobile-messaging-cordova-plugin/releases/tag/3.0.0-rc8
that bug should be fixed there.

**Comment by MerkulovDev** [comment]
yes. ok.

**Comment by MerkulovDev** [comment]
@riskpp  same error
<img width="1055" alt="image" src="https://github.com/infobip/mobile-messaging-cordova-plugin/assets/33004175/e81e1cb6-43ba-4f18-9dbc-1c25ec864ea8">

**Comment by riskpp** [comment]
Hello @MerkulovDev, During plugin version update for 3.0.0-rc8 carthage script should refetch and build framework for new iOS SDK version 10.5.3. How have you updated version? Could you please check which version do you have on the following path: `App/plugins/com-infobip-plugins-mobilemessaging/libs/ios/Carthage/Checkouts/mobile-messaging-sdk-ios/Classes/Core/MMVersion.swift` ?

**Comment by riskpp** [comment]
Yes, version is wrong, should be 10.5.3. 
usually it's enough to call `cordova plugin rm com-infobip-plugins-mobilemessaging` and then `cordova plugin add com-infobip-plugins-mobilemessaging@3.0.0-rc8`.
But you could try to remove `App/plugins/com-infobip-plugins-mobilemessaging/libs/ios/Carthage` folder manually, and then remove plugin.
After adding new version of plugin should be following log (carthage checking out new version of iOS SDK):
```% cordova plugin add ../../../infobip-mobile-messaging-cordova-plugin
Installing "com-infobip-plugins-mobilemessaging" for ios
Installing "cordova-plugin-add-swift-support" for ios
Installing "cordova-custom-config" for ios
Running hook: App/plugins/com-infobip-plugins-mobilemessaging/scripts/build_mobile_messaging_framework.sh 
Building MobileMessaging.xcframework with Carthage started...
*** Checking out mobile-messaging-sdk-ios at "10.5.3"
*** No cache found for mobile-messaging-sdk-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/cp/4z9wq0ld5kz80kyxkvy3tsmm0000gq/T/carthage-xcodebuild.JUrBBB.log
*** Building scheme "MobileMessaging" in MobileMessaging.xcodeproj
Building MobileMessaging.xcframework with Carthage finished.
```

**Comment by MerkulovDev** [comment]
@riskpp 
yep. now it's 10.5.3. 
The issue occurred because I installed the Infobip Mobile Messaging plugin using the command:
ionic cordova plugin add com-infobip-plugins-mobilemessaging@3.0.0 --save
However, I didn't include the -rc8 version specifier.

I'll let you know the outcome after I've conducted some testing.

**Comment by MerkulovDev** [comment]
@riskpp works fine! thx!
