### ISSUE TITLE
Android signed build error

### ISSUE THREAD

**Issue by MerkulovDev** [infobip/mobile-messaging-cordova-plugin#26]
<img width="891" alt="Screenshot 2023-09-06 at 16 44 49" src="https://github.com/infobip/mobile-messaging-cordova-plugin/assets/33004175/d82f0363-0214-4096-a2fd-eb4a4603c4de">
I'am trying to build android app but getting this error.

**Comment by alboldy-ib** [comment]
Hi @MerkulovDev ,

Would you kindly provide the full information on your project, along with MobileMessaging plugin version, package.json and merged AndroidManifest file? 

Geo features are currently not supported, last supported version 2.5.1, recommended version is 3.0.0-rc9.

**Comment by MerkulovDev** [comment]
"com-infobip-plugins-mobilemessaging": "^3.0.0-rc8",

**Comment by alboldy-ib** [comment]
Those receivers are present only in the geofencing sdk - https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-geo-sdk/src/main/AndroidManifest.xml#L37 

However, it is excluded in the 3.0.0-rc versions- https://github.com/infobip/mobile-messaging-cordova-plugin/blob/3.0.0-rc8/libs/android/mobile-messaging-aar.gradle#L45 

I recommend checking if dependencies are fetched correctly, and trying to delete caches. You can also verify within the project files: if `/node_modules/com-infobip-plugins-mobilemessaging/libs/android/mobile-messaging-aar.gradle` is similar to the file mentioned above.

**Comment by riskpp** [comment]
Considering previous comment, I'd also recommend to update the version of the plugin, in https://github.com/infobip/mobile-messaging-cordova-plugin/releases/tag/3.0.1 version geo module isn't included by default.
Closing the issue because no new comments appeared for more than 2 weeks.
