### ISSUE TITLE
Compiled module was created by different version of the compiler

### ISSUE THREAD

**Issue by MerkulovDev** [infobip/mobile-messaging-cordova-plugin#27]
I'm encountering an error following an Xcode update:

```
/Plugins/com-infobip-plugins-mobilemessaging/MobileMessagingCordova.swift
Compiled module was created by a different version of the compiler '5.8.0.124.5'; rebuild 'MobileMessaging' and try again
```

**Comment by alboldy-ib** [comment]
Hello there,

Can you try rebuilding it as described in this article [Module-compiled-with-Swift-x.x.x-cannot-be-imported-by-the-Swift-y.y.y](https://github.com/infobip/mobile-messaging-cordova-plugin/wiki/How-to-fix-issue-after-updating-the-version-of-Xcode-(Module-compiled-with-Swift-x.x.x-cannot-be-imported-by-the-Swift-y.y.y)) ?

**Comment by riskpp** [comment]
There are no more additional comments, so I'll close the issue. It can be opened in case any question will arise.
