### ISSUE TITLE
Ionic build - capacitor support with gradle plugin

### ISSUE THREAD

**Issue by NenadCrncec** [infobip/mobile-messaging-cordova-plugin#28]
When running "npx cap build android" Gradle build reports an error
AILURE: Build failed with an exception.
        
        * Where:
        Script
        ...node_modules/com-infobip-plugins-mobilemessaging/libs/android/mobile-messaging-aar.gradle'
        line: 1
        
        * What went wrong:
        A problem occurred evaluating script.
        > Could not get unknown property 'cdvHelpers' for project ':app' of type org.gradle.api.Project.

Android studio reports an error on gradle sync : Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'cdvHelpers' for project ':app' of type org.gradle.api.Project.

**Comment by riskpp** [comment]
Could you please check on the latest release, I've did this change https://github.com/infobip/mobile-messaging-cordova-plugin/releases/tag/5.1.0
Just be aware that everything [which was done by the hooks](https://github.com/infobip/mobile-messaging-cordova-plugin/blob/master/plugin.xml#L20) on the cordova you'll need to do manually for the Capacitor
