### ISSUE TITLE
Error when received message

### ISSUE THREAD

**Issue by rgfpy** [infobip/mobile-messaging-cordova-plugin#3]
Hi,

I'm having problems when I receive the notification in the APP, but the notification arrives fine, the event .
And the text of the messages on receiving does not show everything in the notifications area, and when you click on the notification when the APP is opened the event "messageReceived" not exec

Version plugin: 0.2.2
Android version: 7.0

I'm using google play services

Using plugin cordova-plugin-google-analytics with google-services.json

Log error:
[error.pdf](https://github.com/infobip/mobile-messaging-cordova-plugin/files/1026280/error.pdf)
![screenshot_20170524-123218](https://cloud.githubusercontent.com/assets/1771656/26414792/39c08ca4-407e-11e7-85d3-3a4202c4dd80.png)

**Comment by stanislavin** [comment]
Hi @rgfpy, thx for reporting this. I am now checking on these two issues:
- text is shortened in notification
- 'messageReceived` may produce exception in cordova plugin

I will post progress here.

**Comment by stanislavin** [comment]
@rgfpy I released [0.2.3](https://github.com/infobip/mobile-messaging-cordova-plugin/releases/tag/0.2.3) with fixes for these issues.

Please try it out and let me know if the issues are gone from your side, so we can close this.

**Comment by rgfpy** [comment]
Hi, @stanislavin i tested now and Work Fine now, the event "messageReceived" ejecuted when opened the APP and the notificacion area the words show all text.

The only thing that would be good for an upcoming update is that being in the APP open and a notification arrives that when the event "messageReceived" disappears and the message disappears from the notifications area but it is not affected at all.

Thanks for your support

**Comment by stanislavin** [comment]
@rgfpy thanks for feedback. We will consider cancellation of notifications as an additional feature for future releases. Just FYI that now the notification will be auto-dismissed if you click on it. But if you open an app from the icon, it has to be handled separately.

Closing this issue.
