### ISSUE TITLE
message.title Undefined

### ISSUE THREAD

**Issue by rgfpy** [infobip/mobile-messaging-cordova-plugin#4]
Hi, in the documentation text describes the properties i cand access with 'message' objet in MessageReceived Event
[message: {
    messageId: '<unique message id>',
    **title: '<title, optional>',**
    body: '<message text>',
    sound: '<notification sound, optional>',
    vibrate: '<true/false, notification vibration setting (Android only)>',
    icon: '<notification icon, optional (Android only)>',
    silent: '<true/false, disables notification for message>',
    category: '<notification category (Android only)>',
    receivedTimestamp: '<absolute timestamp in milliseconds that indicates when the message was received>',
    customData: '<any custom data provided with message>',
    originalPayload: '<original payload of message (iOS only)>',
    contentUrl: '<media content url if media provided>'
}](url)

But the **title** properties not received or whats is the parameter name to send via JSON HTTP API
Here the documentation:
```
POST /push/2/message/single HTTP/1.1
Host: api.infobip.com
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
Content-Type: application/json
Accept: application/json

{
    "from": "d417d38814740a23f50b5c876e226445-0f700564-abbf-4b5b-beae-86a4ef410904",
    "to": {
        "externalUserId": "customer_21234"
    },
    "text": "This Message was sent by targeting exact externalUserId.",
    "notificationOptions": {
      "soundEnabled": false,
      "badge": "1"
    },
    "customPayload":{
      "targetUrl": "www.someDomain.com",
      "someData": "someData"
   }
}
```

Whats parameter name to send "title" data to receive in APP with the plugin

**Comment by stanislavin** [comment]
@rgfpy title now is an experimental feature and is not properly documented. It is only supported in Android. You can try to set it via HTTP API: **notificationOptions.title**.

**Comment by rgfpy** [comment]
Thank for you fast response! 
I tested with notificationOptions.title and work fine with Android

Regards!

**Comment by stanislavin** [comment]
Closing.
