### ISSUE TITLE
Plugin compatibility with Firebase

### ISSUE THREAD

**Issue by rgfpy** [infobip/mobile-messaging-cordova-plugin#8]
I get error when installed Firebase Plugins i need use Firebase Analytics but when installed the bots plugins not compiled with gradle

The plugin using is: **cordova plugin add cordova-plugin-firebase-analytics --save**

Some ideas for fix and then work bots plugis?

Regards

**Comment by kas-kad** [comment]
Hello, we'll check the issue and get back to you as soon as possible.

**Comment by riskpp** [comment]
Hi @rgfpy, we investigated the issue, seems that it's connected with different firebase versions used by MobileMessaging plugin and FirebaseAnalytics plugin. In order to fix this you will need to enforce one single version for both plugins.

You will need to change `com.google.firebase:firebase-core` version  to `10.2.1` in /platforms/android/project.properties file
initially it looks like
`cordova.system.library.1=com.google.firebase:firebase-core:11.0.+`
you can change it to 
`cordova.system.library.1=com.google.firebase:firebase-core:10.2.1`

Let us know is it suits for you, further assistance needed.

**Comment by kas-kad** [comment]
@rgfpy please provide us with your feedback regarding the solution we proposed. Is this issue still relevant or can be closed?

**Comment by rgfpy** [comment]
yes, I had first tried it that way since the android studio demanded me but it does not work.

The result code by Gradle compiler console is:
C:\Android\Apps\appupap\platforms\android\app\src\main\AndroidManifest.xml Error:
	Attribute permission#com.rgfpy.intraupap.permission.C2D_MESSAGE@name value=(.permission.C2D_MESSAGE) from (unknown)
	is also present at [com.google.firebase:firebase-iid:10.2.1] AndroidManifest.xml:24:17-71 value=(com.rgfpy.intraupap.permission.C2D_MESSAGE).
	Suggestion: add 'tools:replace="android:name"' to <permission> element at AndroidManifest.xml:17:5-19:47 to override.
C:\Android\Apps\appupap\platforms\android\app\src\main\AndroidManifest.xml Error:
	Attribute uses-permission#com.rgfpy.intraupap.permission.C2D_MESSAGE@name value=(.permission.C2D_MESSAGE) from (unknown)
	is also present at [com.google.firebase:firebase-iid:10.2.1] AndroidManifest.xml:26:22-76 value=(com.rgfpy.intraupap.permission.C2D_MESSAGE).
	Suggestion: add 'tools:replace="android:name"' to <uses-permission> element at AndroidManifest.xml:15:5-63 to override.

**Comment by stanislavin** [comment]
@rgfpy please use latest version of Infobip Cordova plugin. The problem you described was fixed and Android sdk and integrated in Cordova sdk 0.4.3, should no longer persist.

**Comment by stanislavin** [comment]
@rgfpy let us know if it worked for you

**Comment by rgfpy** [comment]
I tried to install but not working not get from git repository

With command: cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.4.4
and  cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.4.4 --not-fetch --save

Others plugins install correctly

**Comment by stanislavin** [comment]
You are using wrong command line flags:
`--not-fetch`
should be:
`--nofetch`

**Comment by rgfpy** [comment]
Yes that is what I use the one in the documentation cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.4.4 --nofetch --save The flag --not-fetch i only wrote from memory

**Comment by rgfpy** [comment]
I used Windows 10 with tried with power shell and CMD

**Comment by stanislavin** [comment]
Can you please provide command line output here? thx

**Comment by rgfpy** [comment]
I do not receive any message when executing it simply hangs up, but if I install another plugin from a Git repository I install it without problems.

I tried update the cordova in the last version 8.x the same does not work

**Comment by rgfpy** [comment]
![captura](https://user-images.githubusercontent.com/1771656/34302585-57092eea-e710-11e7-9c82-2c18f93b2d3f.JPG)

Yes is slow to install jeje now installe success, but yet the error in screen attach

**Comment by rgfpy** [comment]
Now worked for me.

Changed the librarys version to 11.0.4 from 10.2.1 and add the Compile play services to these version
in dependencies section
`compile 'com.google.android.gms:play-services:11.0.4'`

**Comment by stanislavin** [comment]
Ok, closing.
