### ISSUE TITLE
Problem with fetch plugin

### ISSUE THREAD

**Issue by solinder** [infobip/mobile-messaging-cordova-plugin#9]
Hello
**My environment info:**
    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0
global packages:
    cordova (Cordova CLI) : 7.1.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v8.11.3
    npm  : 5.6.0
    OS   : Windows 10

**My dependencies in package.json:**
"dependencies": {
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/app-preferences": "4.6.0",
    "@ionic-native/camera": "4.4.2",
    "@ionic-native/core": "4.6.0",
    "@ionic-native/http": "4.6.0",
    "@ionic-native/network": "4.6.0",
    "@ionic-native/sim": "4.6.0",
    "@ionic-native/splash-screen": "4.6.0",
    "@ionic-native/status-bar": "4.6.0",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",
    "@types/moment-timezone": "0.5.4",
    "com-infobip-plugins-mobilemessaging": "https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.7.1",
    "cordova-android": "6.3.0",
    "cordova-android-support-gradle-release": "1.2.1",
    "cordova-custom-config": "5.0.2",
    "cordova-plugin-add-swift-support": "1.7.2",
    "cordova-plugin-advanced-http": "1.11.1",
    "cordova-plugin-app-preferences": "0.99.3",
    "cordova-plugin-camera": "4.0.2",
    "cordova-plugin-crosswalk-webview": "2.4.0",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-ionic-webview": "1.1.16",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-screen-orientation": "3.0.1",
    "cordova-plugin-sim": "1.3.3",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.1",
    "cordova-plugin-whitelist": "1.3.3",
    "es6-promise-plugin": "4.2.2",
    "infobip-mobile-messaging-cordova-plugin": "git+https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.7.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "2.2.1",
    "ionicons": "3.0.0",
    "moment": "2.21.0",
    "moment-timezone": "0.5.14",
    "rxjs": "5.5.8",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.20"
  }

When i'm doing `ionic cordova platform add android` i get this error:
![image](https://user-images.githubusercontent.com/26798247/42101278-5952474a-7bcb-11e8-9b0b-f15fed4dacdb.png)

Yesterday it was fine, but today i get this error.
Can you advise me something? Thanks.

**Comment by kas-kad** [comment]
Hi, we'll look into this! For now, could you please try `ionic cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.0 --nofetch --save` in order to install the plugin separately?

**Comment by kas-kad** [comment]
In your package.json try to remove the line with `com-infobip-plugins-mobilemessaging: ...`

**Comment by solinder** [comment]
I cleared my package.json and try to install plugin again.

**My dependencies in package.json:**
"dependencies": {
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/app-preferences": "4.6.0",
    "@ionic-native/camera": "4.4.2",
    "@ionic-native/core": "4.6.0",
    "@ionic-native/http": "4.6.0",
    "@ionic-native/network": "4.6.0",
    "@ionic-native/sim": "4.6.0",
    "@ionic-native/splash-screen": "4.6.0",
    "@ionic-native/status-bar": "4.6.0",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",
    "@types/moment-timezone": "0.5.4",
    "cordova-android-support-gradle-release": "1.2.1",
    "cordova-custom-config": "5.0.2",
    "cordova-plugin-add-swift-support": "1.7.2",
    "cordova-plugin-advanced-http": "1.11.1",
    "cordova-plugin-app-preferences": "0.99.3",
    "cordova-plugin-camera": "4.0.2",
    "cordova-plugin-crosswalk-webview": "2.4.0",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-ionic-webview": "1.1.16",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-screen-orientation": "3.0.1",
    "cordova-plugin-sim": "1.3.3",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.1",
    "cordova-plugin-whitelist": "1.3.3",
    "es6-promise-plugin": "4.2.2",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "2.2.1",
    "ionicons": "3.0.0",
    "moment": "2.21.0",
    "moment-timezone": "0.5.14",
    "rs-plugin-datepicker": "1.0.1",
    "rs-plugin-device-info": "1.0.0",
    "rs-plugin-fingerprint": "1.3.3",
    "rs-plugin-touchid": "1.1.1",
    "rxjs": "5.5.8",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.20"
  },

**Command for installing the plugin:**
`ionic cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.0 --save`

**Error:**
![image](https://user-images.githubusercontent.com/26798247/42152768-db260f66-7de9-11e8-8f99-1f02cf2d2123.png)

**Comment by kas-kad** [comment]
The issue you're experiencing now is related to git command execution. For some reason, Windows can't perform 'git submodule update'. Make sure you have administrative rights to perform terminal commands. There might be other causes for this issue though.

**Comment by kas-kad** [comment]
Also, in the picture you can find complete log of the run, the *-debug.log file. These logs may help to debug the issue.

**Comment by solinder** [comment]
I noticed that when installing plugin with flag `--nofetch` it is ok and no errors ocured:
`cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.0 --nofetch --save`
But without this flag it is not ok such as in my previous messages.

Why is this flag is required when installing plugin?
The problem is that project is build automatically. All dependencies are loaded from packege.json, and then platform is added. And it is not clear how to add flag `--nofetch` to packege.json. I guess that it is not possible to install plugin with this flag while doing `npm install`.

**Comment by kas-kad** [comment]
Thank you for the information. I can confirm that my test project builds without `--nofetch`. For now it is not a necessary flag for adding the plugin. Let me know if any issues appear in future.

**Comment by solinder** [comment]
Thank you. Does this plugin support cordova 8.0?

**Comment by kas-kad** [comment]
there were no issues with Cordova 8.0 that we're aware of.

**Comment by solinder** [comment]
In plugin.xml there is such string:
`id="com-infobip-plugins-mobilemessaging"`
In packege.json the name of the plugin is:
`"name": "infobip-mobile-messaging-cordova-plugin",`

I think that **id** and **name** should be equal.
Now i install the plugin and get such code in my package.json and config.xml:
`"infobip-mobile-messaging-cordova-plugin": "git+https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.0",`
`<plugin name="com-infobip-plugins-mobilemessaging" spec="https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.0" />`

Then if i make `npm install` i get this new line in my package.json:
`"com-infobip-plugins-mobilemessaging": "https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.7.1",`
As the result there are two lines for this plugin in packege.json. You saw them in my first message.

What do you think about id in plugin.xml and name in package.json?

**Comment by kas-kad** [comment]
Thank you for pointing out the issue. As nor we or out clients haven't ever used nmp for plugin installation, we missed this misconfiguration.

**Comment by rstylesoftlab** [comment]
In file www/MobileMessagingCordova.js there is such string:
`cordova.require("cordova/plugin_list").metadata["com-infobip-plugins-mobilemessaging"];`
I guess that this shoud be changed to actual plugin name.

Also in directories /tests/, /example/ and in file README.md it may be usefull to change this name too.

**Comment by solinder** [comment]
I'm using new plugin release 0.8.3.
My steps:
1. Install clear test Ionic app using:
`ionic start testApp blank`
2. Install plugin using:
`ionic cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.3 --save`
3. Add platform using:
`ionic cordova platform add android`
4. Get error:
![image](https://user-images.githubusercontent.com/26798247/42224846-bd9caa54-7ee3-11e8-9928-3537f9945eaf.png)

I have tried several times: on my working app and on Ionic blank app. On Windows and on MacOs. This error still exists.

Ionic info:
![image](https://user-images.githubusercontent.com/26798247/42224978-1bb42ef0-7ee4-11e8-8c7e-a4b65c460aa9.png)

Plugins in config.xml:
 <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="com-infobip-plugins-mobilemessaging" spec="https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.3" />

Package.json:
{
  "name": "testApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "4.8.0",
    "@ionic-native/splash-screen": "4.8.0",
    "@ionic-native/status-bar": "4.8.0",
    "@ionic/storage": "2.1.3",
    "com-infobip-plugins-mobilemessaging": "git+https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-add-swift-support": "1.7.2",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "com-infobip-plugins-mobilemessaging": {}
    }
  }
}

**Comment by kas-kad** [comment]
@solinder I can't reproduce the issue, please check my output, where I repeat your three steps  https://pastebin.com/tVAYyHPs

```
ionic 3.20.0
npm 5.3.0
git version 2.15.2 (Apple Git-101.1)
cordova 8.0.0
```

**Comment by solinder** [comment]
I think I understood what is my problem.
When I add a platform the url of the plugin in packege.json is changing from:
`"com-infobip-plugins-mobilemessaging": "https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.3",`
to:
`"com-infobip-plugins-mobilemessaging": "git+https://github.com/infobip/mobile-messaging-cordova-plugin.git#0.8.3",`

**Comment by solinder** [comment]
I think this "git+" part of url is added automatically because of this part of your package.json:
```
"repository": {
    "type": "git",
    "url": "git+https://github.com/infobip/mobile-messaging-cordova-plugin.git"
  },
```

**Comment by kas-kad** [comment]
@solinder I have the same "git+https" in my package.json. It works fine for me. I will try to remove this "git" part from our package.json and check if it works fine afterwards.

**Comment by kas-kad** [comment]
@solinder I've just tested what happens if I use "https" instead of "git+https" in our package.json. After the plugin is added to the test project, the project's package.json continues appending "git+": "git+https". However, can you try the same with:
```
ionic cordova plugin add https://github.com/infobip/mobile-messaging-cordova-plugin.git --save
```

**Comment by kas-kad** [comment]
@solinder I've just manually published the plugin to npm. You can try it `ionic cordova plugin add com-infobip-plugins-mobilemessaging  --save`

**Comment by solinder** [comment]
I installed plugin using npm. Now it works fine for me.
Thank you!!
